version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - ./infra/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: db_agendador

  usuario:
    image: sindoval/usuario:latest
    container_name: usuario
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db_usuario
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - postgres

  agendador-tarefas:
    image: sindoval/agendador-tarefas:latest
    container_name: agendador-tarefas
    ports:
      - "8082:8082"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/db_agendador
      USUARIO_URL: http://usuario:8081/usuario
    depends_on:
      - mongo

  comunicacao:
    image: sindoval/comunicacao:latest
    container_name: comunicacao
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db_comunicacao
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      NOTIFICACAO_URL: http://notificacao:8083/email
    depends_on:
      - postgres

  notificacao:
    image: sindoval/notificacao:latest
    container_name: notificacao
    ports:
      - "8083:8083"
    env_file:
      - .env

  bff-agendador:
    image: sindoval/bff-agendador-tarefas:latest
    container_name: bff-agendador
    ports:
      - "8084:8084"
    env_file:
      - .env
    environment:
      - USUARIO_URL=http://usuario:8081/usuario
      - TAREFAS_URL=http://agendador-tarefas:8082/tarefas
      - NOTIFICACAO_URL=http://notificacao:8083/email
      - COMUNICACAO_URL=http://comunicacao:8085/comunicacao
      - DB_PASSWORD=123
      - TZ=America/Sao_Paulo
    depends_on:
      - usuario
      - agendador-tarefas
      - comunicacao

networks:
  default:
    driver: bridge